spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db01
    username: root
    password: 159357wmwm
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    #开启mybatis的日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启驼峰命名自动映射
    map-underscore-to-camel-case: true